-- Active: 1767705706205@@127.0.0.1@5432@echange
CREATE DATABASE echange;

-- Drop tables with CASCADE to handle foreign key constraints
DROP TABLE IF EXISTS echange CASCADE;
DROP TABLE IF EXISTS produits CASCADE;
DROP TABLE IF EXISTS status CASCADE;
DROP TABLE IF EXISTS categorie CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admins(
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categorie(
    id SERIAL PRIMARY KEY,
    nom VARCHAR(255) NOT NULL
);

CREATE TABLE produits(
    id SERIAL PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    description TEXT,
    id_proprietaire INT REFERENCES users(id) ON DELETE CASCADE,
    id_categorie INT REFERENCES categorie(id) ON DELETE CASCADE,
    prix DECIMAL(10, 2) NOT NULL,
    disponible BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE status(
    id SERIAL PRIMARY KEY,
    nom VARCHAR(50) NOT NULL
);  

CREATE TABLE echange(
    id SERIAL PRIMARY KEY,
    id_produit1 INT REFERENCES produits(id) ON DELETE CASCADE,
    id_produit2 INT REFERENCES produits(id) ON DELETE CASCADE,
    id_proprietaire INT REFERENCES users(id) ON DELETE CASCADE,
    id_acheteur INT REFERENCES users(id) ON DELETE CASCADE,
    id_status INT REFERENCES status(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



